version: "3"
services: 
  db:
    image: mariadb:10.2.32-bionic
    container_name: saojeng-mariadb-10.2.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "bs0j7NJR!"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/data/saojeong/:/var/lib/mysql
      - ./all_dbs.sql:/docker-entrypoint-initdb.d/all_dbs.sql
